### ISSUE TITLE
Implement `uniwig`

### ISSUE THREAD

**Issue by nleroy917** [databio/gtars#1]
To enable `universe` creation, we will need to port [`uniwig`](https://github.com/databio/uniwig) over to this package and offer it up as a `cli`, a library crate interface, and ideally a python interface.

**Comment by donaldcampbelljr** [comment]
This still needs python bindings before it can properly be closed.

**Comment by nleroy917** [comment]
What do we want the ergonomics to be like here?
```python
from gtars.uniwig import uniwig

uniwig(
  combined_bed="/path/to/file.bed",
  smooth_size=10,
  step_size=5,
  ...
)
```
Could it be that simple? Does it need a python interface then?

**Comment by donaldcampbelljr** [comment]
Once we release the newest uniwig changes to master branch, we can close this issue and create new ones that are more specific to future enhancements.

**Comment by donaldcampbelljr** [comment]
Per above comment, I'm going to close this and refer to more specific uniwig issues.
