### ISSUE TITLE
uniwig's meta file output is same for start and end

### ISSUE THREAD

**Issue by ClaudeHu** [databio/gtars#61]
I ran `gtars.uniwig` (`master` branch) with `gtars/tests/data/consensus/consensus1.bed` as the input and `gtars/tests/hg38.chrom.sizes` as the chromosome reference:

```
cargo run uniwig -f $GTARS/gtars/tests/data/consensus/consensus1.bed -c $GTARS/gtars/tests/hg38.chrom.sizes -m 100 -s 10 -l $OUTPUT -y npy
```

In the outputs, both `end.meta` and `start.meta` are exactly same:

```
fixedStep chrom=chrX start=50 step=10
fixedStep chrom=chr3 start=500 step=10
fixedStep chrom=chr2 start=300 step=10
fixedStep chrom=chr1 start=1 step=10
```

**Comment by donaldcampbelljr** [comment]
Thanks for the heads up. I believe I've fixed this in the dev branch with the above commit. Pull that and give it a go.

**Comment by ClaudeHu** [comment]
`dev` fixed that issue
